# Generated by Django 5.1.4 on 2025-01-12 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='publishcourse',
            name='admin_text',
            field=models.TextField(max_length=500, null=True),
        ),
    ]
